tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mongodb/brew"
brew "krb5"
brew "mongosh"
brew "node", link: false
brew "node@14"
brew "postgresql@14"
brew "python@3.10"
brew "wget"
brew "yarn"
brew "mongodb/brew/mongodb-community"
cask "iterm2"
cask "slack"
